language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
before_install:
  - "mkdir -p ~/.npm"
install:
  - npm install
  - npm install git://github.com/hybridgroup/cylon.git
  - npm install -g jshint istanbul codeclimate-test-reporter
script:
  - make ci
  - CODECLIMATE_REPO_TOKEN=9c44fbd3cc00c454a65a555f55d176b1fa81f58ef13f7c508ddd7dfd48dffcb4 codeclimate-test-reporter < coverage/lcov.info
